[options]
addons_path = /mnt/extra-addons,/mnt/common18/custom,/mnt/common18/custom_paid,/mnt/common18/custom-paid,/mnt/common18/custom paid
data_dir = /var/lib/odoo
admin_passwd = Enter@123!
http_port = 8001
db_host = db
db_port = 5432
db_user = odoo
db_password = Enter@123!
dbfilter = template-ibizasunpower
proxy_mode = True

