[options]
addons_path = /mnt/extra-addons,/mnt/common19/custom
data_dir = /var/lib/odoo
admin_passwd = Enter@123!
http_port = 8002
db_host = db
db_port = 5432
db_user = odoo
db_password = Enter@123!
dbfilter = odoo19-template
